version: '3'

services:

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: unless-stopped
    environment:
      ASR_MODEL: small
    ports:
      - "9000:9000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  libretranslate:
    container_name: libretranslate
    image: edwardyliu/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  voicevox:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    restart: unless-stopped
    ports:
      - "50021:50021"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]